# Key bindings for custom apps.

# Floating terminal window running python, for ad-hoc calculations.
for_window [app_id="terminal-floating"] floating enable
bindsym $mod+Semicolon exec '$term --app-id=terminal-floating python3'
